### ISSUE TITLE
Problème Encodage

### ISSUE THREAD

**Issue by marsu1983** [Roromis/Lalf-Forumactif#13]
Bonjour,

Lorsque je lance le script, je récupère bien TID etc et au moment de récupérer les topics, j'ai ce message:

Traceback (most recent call last):
  File "./forumactif-phpbb.py", line 430, in <module>
    etapes[i]()
  File "./forumactif-phpbb.py", line 195, in get_topics
    result = re.search('function do_pagination_start\(\)[^\}]*start = \(start > \d+\) \? (\d+) : start;[^\}]*start = \(start - 1\) \* (\d+);[^\}]*\}', d.text())
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 821, in text
    add_text(tag, no_tail=True)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 816, in add_text
    add_text(child)
  File "/root/Roromis-Lalf-Forumactif-dbf1a8a/pyquery/pyquery.py", line 813, in add_text
    if tag.text:
  File "lxml.etree.pyx", line 815, in lxml.etree._Element.text.__get__ (src/lxml/lxml.etree.c:33236)
  File "apihelpers.pxi", line 616, in lxml.etree._collectText (src/lxml/lxml.etree.c:15062)
  File "apihelpers.pxi", line 1280, in lxml.etree.funicode (src/lxml/lxml.etree.c:20049)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 525: invalid continuation byte

Avez vous une idée ? (je pense pour un problème d'encodage au niveau de python mais je suis bien en utf-8, j'ai bien vérifié) 

Bonne journée

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf.
