### ISSUE TITLE
Erreur en récupération des sujets : illegal multibyte sequence

### ISSUE THREAD

**Issue by Flo2** [Roromis/Lalf-Forumactif#23]
Salut !

J'ai un souci en récupération des sujet :

21/08/2013 14:16:12 - DEBUG    : Récupération : sujet 663
21/08/2013 14:16:16 - ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "C:\Users\Florent\Desktop\Lalf-Forumactif-master\forumactif-phpbb.py", line 436, in <module>
    etapes[i]()
  File "C:\Users\Florent\Desktop\Lalf-Forumactif-master\forumactif-phpbb.py", line 213, in get_topics
    d = PyQuery(url=config.rooturl + '/' + forum['type'] + str(forum['id']) + 'p' + str(page*topicsperpages) + '-a', opener=fa_opener)
  File "C:\Users\Florent\Desktop\Lalf-Forumactif-master\pyquery\pyquery.py", line 170, in __init__
    html = opener(url, **kwargs)
  File "C:\Users\Florent\Desktop\Lalf-Forumactif-master\forumactif-phpbb.py", line 127, in fa_opener
    return unicode(data, chardet.detect(data)['encoding'])
UnicodeDecodeError: 'gb2312' codec can't decode bytes in position 692-693: illegal multibyte sequence

Est-ce que quelqu'un aurait une idée svp ? :(

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf.
