### ISSUE TITLE
Erreur : "TypeError: expected string or buffer"

### ISSUE THREAD

**Issue by lemaddog** [Roromis/Lalf-Forumactif#32]
Le lancement de la récupération de la base de donnée s'arrête à "membre" et me donne à chaque fois cela : 

Traceback (most recent call last):
  File "./forumactif-phpbb.py", line 436, in <module>
    etapes[i]()
  File "./forumactif-phpbb.py", line 264, in get_users
    id = int(re.search("&u=(\d+)&", e("td a").eq(0).attr("href")).group(1))
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

Si quelqu'un a un moyen de me dépanner.

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'une ancienne version du Lalf.
