### ISSUE TITLE
Problèmes Lalf 2 & Lalf 3

### ISSUE THREAD

**Issue by Bloufit** [Roromis/Lalf-Forumactif#33]
Bonjour à tous !
Bon bah voilà, cela fait très longtemps que j'essaye de faire fonctionner le Lalf... J'avance, mais doucement. (Voici la début de mes mésaventures :  http://forums.phpbb-fr.com/message1572997.html#p1572997 )

Lalf 2
=====
Je suis donc avec le Lalf V2 modifié de MathieuMa ( https://github.com/MathieuMa/Lalf-Forumactif/ ), et pour le moment, seul mes Forums sont sauvegardés. Mais j'ai maintenant ce joli machin :
ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "C:\FA\Lalf 2 MathieuMa\forumactif-phpbb.py", line 564, in <module>
    etapes[i]()
  File "C:\FA\Lalf 2 MathieuMa\forumactif-phpbb.py", line 302, in get_users
    currentpage = int(n/usersperpages)
ZeroDivisionError: integer division or modulo by zero
INFO     : Sauvegarde de la progression

Quelqu'un a une idée ?

Bon, je ne me suis pas arrêté là, donc j'ai mis le fichier "Save.py" dans le Lalf de Non-Modifié, et j'ai ce truc :
Traceback (most recent call last):
  File "C:\FA\Lalf 2 Roromis\forumactif-phpbb.py", line 559, in <module>
    n = max([i["newid"] for i in save.users])
ValueError: max() arg is an empty sequence

Une autre idée ?

Et j'ai retesté avec le lalf du Supermanu, et ça fait cette jolie chose :
 ERROR    : Une erreur s'est produite. Essayez de relancer le script. Pour plus d'informations, consultez le fichier debug.log.
Traceback (most recent call last):
  File "C:\Forum Actif\Lalf 2.2 Supermanu\forumactif-phpbb.py", line 528, in <module>
    etapes[i]()
  File "C:\Forum Actif\Lalf 2.2 Supermanu\forumactif-phpbb.py", line 306, in get_users
    id = int(re.search("/u(\d+)", e("td span a").eq(0).attr("href")).group(1))
  File "C:\Python27\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
 INFO     : Sauvegarde de la progression

Alors ?

Lalf 3
=====
J'ai donc tout : Python32, Lxml, Pip et tout le reste de la famille du Lalf, quand j’exécute : C:\Python32\python.exe C:\Lalf\lalf.py, j'ai ceci :
Traceback (most recent call last):
File "lalf.py", line 19, in <module>
from lalf import main
File "C:\Lalf\lalf\__init__.py", line 28, in <module>
from lalf.bb import load, BB
File "C:\Lalf\lalf\bb.py", line 30, in <module>
from lalf.forums import Forums
File "C:\Lalf\lalf\forums.py", line 25, in <module>
from lalf.forum import Forum
File "C:\Lalf\lalf\forum.py", line 29, in <module>
from lalf.forumpage import ForumPage
File "C:\Lalf\lalf\forumpage.py", line 64
locked = u"verrouillé" in f("td img").eq(0).attr("alt")
^
SyntaxError: invalid syntax

Toutes les idèes sont les bienvenues ! (Je vais ouvrir un site internet rien que pour ce problème  :D )

Voilà, en espérant que quelqu'un pourra m'aider !

**Comment by Roromis** [comment]
Je ferme ce rapport qui traite d'anciennes versions du Lalf. Si vous avez ce problème avec la dernière version, ouvrez un nouveau rapport de bug.
