### ISSUE TITLE
LookupError: unknown encoding: base64 (Python 3.3.2)

### ISSUE THREAD

**Issue by jeancf** [Roromis/Lalf-Forumactif#37]
Juste après l'extraction des adresses mail des utilisateurs l'application balance une exception:

    Traceback (most recent call last):
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf.py", line 22, in <module> main()
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/__init__.py", line 64, in main bb.dump(f)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 82, in dump c.dump(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 82, in dump c.dump(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 82, in dump c.dump(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 82, in dump c.dump(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 82, in dump c.dump(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 82, in dump c.dump(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/node.py", line 79, in dump self._dump_(file)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/post.py", line 60, in _dump_post, uid, bitfield, checksum = phpbb.format_post(self.post)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/phpbb.py", line 245, in format_post bitfield = makebitfield(post)
    File "/home/jeancf/PycharmProjects/Lalf-Forumactif/lalf/phpbb.py", line 237, in makebitfield return codecs.encode(''.join([chr(c) for c in bf]).rstrip('\0').encode("utf8"), 'base64').strip()
    LookupError: unknown encoding: base64

Après recherche dans la doc, il faut remplacer 'base64' par 'base64_codec' dans la ligne 237 de phpbb.py:
```python
    return codecs.encode(''.join([chr(c) for c in bf]).rstrip('\0').encode("utf8"), 'base64_codec').strip()
```
Après ça, ça roule raoul!

**Comment by idaho1** [comment]
Bonjour,
j' ai apporté la correction, mais il me reste les autres erreurs : 
`Traceback (most recent call last):

  File "lalf.py", line 22, in <module>  main()

  File "/blabla/Lalf-Forumactif-3/lalf/__init__.py", line 64, in main    bb.dump(f) 

  File "/blabla/Lalf-Forumactif-3/lalf/node.py", line 82, in dump    c.dump(file)

  File /blabla/Lalf-Forumactif-3/lalf/node.py", line 82, in dump    c.dump(file)

  File "/blabla/Lalf-Forumactif-3/lalf/node.py", line 82, in dump    c.dump(file)

  File /blabla/Lalf-Forumactif-3/lalf/node.py", line 82, in dump    c.dump(file)

  File "/blabla/Lalf-Forumactif-3/lalf/node.py", line 79, in dump    self._dump_(file)

  File "/blabla/Lalf-Forumactif-3/lalf/topic.py", line 81, in _dump_    posts[0]`

**Comment by jeancf** [comment]
Je n'ai plus touché à cet outil depuis des années.

Le message signifie que le programme essaye de lire au delà du dernier élément de la liste. Il semblerait donc que `posts` soit vide. essayez d'effacer tout les fichiers temporaires et de recommencer l'import depuis le début. Je me souviens que le redémarrage après un problème est souvent problématique.

Bonne chance,

jeancf
