### ISSUE TITLE
error in lalf3

### ISSUE THREAD

**Issue by minisquall** [Roromis/Lalf-Forumactif#41]
Please help me ! 
Error is : 

Traceback (most recent call last):
  File "lalf.py", line 22, in <module>
    main()
  File "/home/pierre/Bureau/lalf/__init__.py", line 45, in main
    bb = load()
  File "/home/pierre/Bureau/lalf/bb.py", line 126, in load
    bb = pickle.load(f)
  File "/home/pierre/Bureau/lalf/bb.py", line 93, in __setstate__
    counters.topictotal = self.nbtopics
AttributeError: 'BB' object has no attribute 'nbtopics'
Solution?

**Comment by Roromis** [comment]
Si ce problème arrive de nouveau avec la dernière version du Lalf, supprimez le fichier save.pickle.

You should try to use the last version of the Lalf. If this happens again, delete the save.pickle file.
