### ISSUE TITLE
Erreur sur les sous-catégories

### ISSUE THREAD

**Issue by Knight2050** [Roromis/Lalf-Forumactif#50]
Je rencontre un bug lors de la lecture des sous-catégories du forum. J'ai essayé de bouger l'archi du forum mais le bug persiste sur la première sous-catégorie qu'il rencontre.

[debug.txt](https://github.com/Roromis/Lalf-Forumactif/files/221106/debug.txt)

> INFO     : Lalf 3.0a0
> DEBUG    : OS : win32
> INFO     : Récupération des forums
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> DEBUG    : Récupération du tid
> INFO     : Sauvegarde de l'état courant.
> ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (ValueError("invalid literal for int() with base 10: 'Charte & Communication'",)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
> https://github.com/Roromis/Lalf-Forumactif/issues
> Traceback (most recent call last):
>   File "C:\Users\Knight2050\Miniconda3\lib\site-packages\lalf\__init__.py", line 58, in main
>     bb.export()
>   File "C:\Users\Knight2050\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
>     child.export()
>   File "C:\Users\Knight2050\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
>     self._export_()
>   File "C:\Users\Knight2050\Miniconda3\lib\site-packages\lalf\forums.py", line 238, in _export_
>     self.get_subforums_infos(response.text)
>   File "C:\Users\Knight2050\Miniconda3\lib\site-packages\lalf\forums.py", line 270, in get_subforums_infos
>     self.forums[oldid].num_topics = int(row("td").eq(2).text())
> ValueError: invalid literal for int() with base 10: 'Charte & Communication'

Les étapes de récupération des groupes et membres juste avant ce passe sans encombre.

Merci d'avance.

**Comment by Roromis** [comment]
Ton forum utilise bien un thème phpbb2? Si ce n'est pas le cas, crée un [thème temporaire](https://roromis.github.io/Lalf-Forumactif/annexes/theme-temporaire.html).

Si c'est bien le cas, peux-tu m'envoyer l'adresse de ton forum à l'adresse `lalf arobase openmailbox point org` pour que j'essaye de voir d'où vient le problème?

**Comment by Knight2050** [comment]
J'ai pu finir l’exécution du script en retirant toute les sous-catégories pour en faire des catégories à par entière.

**Comment by Roromis** [comment]
Il y a beaucoup d'options pour configurer la page d'accueil, je ne devrais probablement pas l'utiliser pour exporter les forums.... J'essayerai de corriger ça dès que possible. En attendant, si vous avez le même problème, dans le panneau d'administration, ouvrez l'onglet *Affichage*, cliquez sur le lien *Page d'accueil* > *Structure et hiérarchie* dans le menu à gauche, puis sous **Séparer les catégories sur l'index**, sélectionnez *Moyen*.
