### ISSUE TITLE
Lancement du script

### ISSUE THREAD

**Issue by zoch27** [Roromis/Lalf-Forumactif#54]
Je n'ai pas pu lancé, car je ne sais pas comment faire, je suis dans le dossier C:\Laft, mais rien ne se passe, que dois-je faire merci ;)

**Comment by Roromis** [comment]
Bonjour,

Je ne peux pas t'aider si je n'ai pas plus d'informations. Suis le [manuel](https://roromis.github.io/Lalf-Forumactif/installation.html#windows), et explique précisément ce que tu as fait et où tu es bloqué.

**Comment by zoch27** [comment]
Bonjour,

Moi je suis ici en fait : 
`Ouvrez un terminal, et placez vous dans le dossier créé à l’étape Installation :
cd $dossier
(remplacez $dossier par le chemin du dossier, par exemple ~/Lalf ou C:\Lalf)
Exécutez la commande suivante :`

Le problème, il y a rien qui ne s’exécute ou bien la commande n'existe pas.

**Comment by Roromis** [comment]
Que se passe-t-il exactement? Y a-t-il un message d'erreur? As-tu eut des problèmes lors de l'étape d'installation?

Envoie moi ce qui est affiché dans ton terminal (copié-collé ou capture d'écran).

**Comment by zoch27** [comment]
oui voici 
![capture](https://cloud.githubusercontent.com/assets/12103679/15361001/225f1252-1d10-11e6-8a9b-72069f9763f4.PNG)

**Comment by zoch27** [comment]
Edit : j'avais fait une erreur dans le mot. La SAV a été fait, mais le phpbb.sql n'a pas été créé, pourquoi ?

**Comment by Roromis** [comment]
Que se passe-t-il quand tu lance la commande `lalf` dans le terminal?

**Comment by zoch27** [comment]
Tout fonctionne, par contre exporter un forum de 15.000 membres, 60.000 messages 11.000 sujets, il y a des erreurs de connexion d'après le script, cela risque rien ?

**Comment by Roromis** [comment]
Les erreurs de connexions sont normales. Tant que le script ne s'interrompt pas, il n'y a pas de problème.

**Comment by zoch27** [comment]
Super, je te dis quand c'est fini.
Merci pour le script, vous êtes le meilleur

**Comment by zoch27** [comment]
![capture](https://cloud.githubusercontent.com/assets/12103679/15373818/a48dd614-1d47-11e6-9b00-9bd7eb7fdd48.PNG)
voici ma nouvelle erreur

**Comment by zoch27** [comment]
Je relance, saviez-vous comment corriger l'erreur ci-dessus ?

**Comment by zoch27** [comment]
J'up

**Comment by zoch27** [comment]
up

**Comment by BanBan55** [comment]
J'ai exactement le meme probleme.

**Comment by BanBan55** [comment]
C:\Lalf>lalf
Lalf 3.0a0
Récupération des statistiques
Sauvegarde de l'état courant.
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (KeyError('Messages',)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "C:\Users\Alban\Miniconda3\lib\site-packages\lalf__init__.py", line 58, in main
    bb.export()
  File "C:\Users\Alban\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
    self._export_()
  File "C:\Users\Alban\Miniconda3\lib\site-packages\lalf\bb.py", line 112, in _export_
    self.total_posts = int(stats["Messages"])
KeyError: 'Messages'
[                                                                                                                ]   0%
