### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Couss** [Roromis/Lalf-Forumactif#61]
Je ne parviens pas a récupérer mon forum.

Ca plante au niveau des formats de date des statistiques mais je pense pas pouvoir le changer

debug.log

> INFO     : Lalf 3.0a0
> DEBUG    : OS : win32
> INFO     : Récupération des statistiques
> DEBUG    : Connection au forum
> DEBUG    : Récupération du sid
> DEBUG    : Récupération du tid
> INFO     : Sauvegarde de l'état courant.
> ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (IndexError('list index out of range',)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
> https://github.com/Roromis/Lalf-Forumactif/issues
> Traceback (most recent call last):
>   File "D:\Programs\Miniconda3\lib\site-packages\lalf__init__.py", line 58, in main
>     bb.export()
>   File "D:\Programs\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
>     self._export_()
>   File "D:\Programs\Miniconda3\lib\site-packages\lalf\bb.py", line 116, in _export_
>     self.startdate = parse_date(stats["Ouverture du forum"])
>   File "D:\Programs\Miniconda3\lib\site-packages\lalf\util.py", line 130, in parse_date
>     post_date = datetime.date(int(post_date[3]), month(post_date[2]), int(post_date[1]))
> IndexError: list index out of range

**Comment by Couss** [comment]
My bad j'ai oublier l'année dans la config de mon profil
