### ISSUE TITLE
(KeyError('f3',))

### ISSUE THREAD

**Issue by DiKiP** [Roromis/Lalf-Forumactif#66]
Bonjour, voici le le fichier debug :
INFO     : Lalf 3.0a0
DEBUG    : OS : win32
INFO     : Récupération des statistiques
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
DEBUG    : Messages : 4
DEBUG    : Sujets : 4
DEBUG    : Membres : 2
INFO     : Récupération des émoticones
DEBUG    : Récupération des émoticones (page 0)
DEBUG    : L'émoticone ":D" existe déjà dans phpbb.
DEBUG    : L'émoticone ":)" existe déjà dans phpbb.
DEBUG    : L'émoticone ":(" existe déjà dans phpbb.
DEBUG    : L'émoticone ":o" existe déjà dans phpbb.
DEBUG    : L'émoticone ":shock:" existe déjà dans phpbb.
DEBUG    : L'émoticone "8)" existe déjà dans phpbb.
DEBUG    : L'émoticone ":lol:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":x" existe déjà dans phpbb.
DEBUG    : L'émoticone ":P" existe déjà dans phpbb.
DEBUG    : L'émoticone ":oops:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":cry:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":evil:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":twisted:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":roll:" existe déjà dans phpbb.
DEBUG    : L'émoticone ";)" existe déjà dans phpbb.
DEBUG    : L'émoticone ":!:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":?:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":idea:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":arrow:" existe déjà dans phpbb.
DEBUG    : L'émoticone ":|" existe déjà dans phpbb.
DEBUG    : Récupération des émoticones (page 20)
INFO     : Téléchargement de l'émoticone ":face:"
INFO     : Téléchargement de l'émoticone ":star:"
INFO     : Téléchargement de l'émoticone ":suspect:"
INFO     : Téléchargement de l'émoticone ":heart:"
INFO     : Téléchargement de l'émoticone ":no:"
INFO     : Téléchargement de l'émoticone ":@:"
INFO     : Téléchargement de l'émoticone ":cyclops:"
INFO     : Téléchargement de l'émoticone ":clown:"
INFO     : Téléchargement de l'émoticone ":pirat:"
INFO     : Téléchargement de l'émoticone ":tongue:"
INFO     : Téléchargement de l'émoticone ":silent:"
INFO     : Téléchargement de l'émoticone ":pale:"
INFO     : Téléchargement de l'émoticone ":alien:"
INFO     : Téléchargement de l'émoticone ":cat:"
INFO     : Téléchargement de l'émoticone ":monkey:"
INFO     : Téléchargement de l'émoticone ":pig:"
INFO     : Téléchargement de l'émoticone ":rabbit:"
INFO     : Téléchargement de l'émoticone ":bounce:"
INFO     : Téléchargement de l'émoticone ":confused:"
INFO     : Téléchargement de l'émoticone ":affraid:"
DEBUG    : Récupération des émoticones (page 40)
DEBUG    : L'émoticone ":geek:" existe déjà dans phpbb.
INFO     : Téléchargement de l'émoticone ":bball:"
INFO     : Téléchargement de l'émoticone ":cheers:"
INFO     : Téléchargement de l'émoticone ":bom:"
INFO     : Téléchargement de l'émoticone ":drunken:"
INFO     : Téléchargement de l'émoticone ":sleep:"
INFO     : Téléchargement de l'émoticone ":sunny:"
INFO     : Téléchargement de l'émoticone ":albino:"
INFO     : Téléchargement de l'émoticone ":cherry:"
INFO     : Téléchargement de l'émoticone ":santa:"
INFO     : Téléchargement de l'émoticone ":rendeer:"
INFO     : Téléchargement de l'émoticone ":farao:"
INFO     : Téléchargement de l'émoticone ":king:"
INFO     : Téléchargement de l'émoticone ":queen:"
INFO     : Téléchargement de l'émoticone ":joker:"
INFO     : Téléchargement de l'émoticone ":scratch:"
INFO     : Téléchargement de l'émoticone ":study:"
INFO     : Téléchargement de l'émoticone ":elephant:"
INFO     : Téléchargement de l'émoticone ":flower:"
INFO     : Téléchargement de l'émoticone ":afro:"
DEBUG    : Récupération des émoticones (page 60)
INFO     : Téléchargement de l'émoticone ":lol!:"
INFO     : Récupération des membres
DEBUG    : Récupération des membres (page 0)
INFO     : Récupération du membre 1
INFO     : Récupération du membre 2
INFO     : Récupération des groupes
INFO     : Récupération du groupe 1
DEBUG    : Récupération du groupe 1 (page 0)
INFO     : Récupération du groupe 2
DEBUG    : Récupération du groupe 2 (page 0)
INFO     : Récupération des forums
INFO     : Sauvegarde de l'état courant.
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (KeyError('f3',)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "C:\Users\DiKiP\Miniconda3\lib\site-packages\lalf\__init__.py", line 58, in main
    bb.export()
  File "C:\Users\DiKiP\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "C:\Users\DiKiP\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
    self._export_()
  File "C:\Users\DiKiP\Miniconda3\lib\site-packages\lalf\forums.py", line 238, in _export_
    self.get_subforums_infos(response.text)
  File "C:\Users\DiKiP\Miniconda3\lib\site-packages\lalf\forums.py", line 262, in get_subforums_infos
    self.forums[oldid].status = 1 if "verrouillé" in alt else 0
KeyError: 'f3'

J'ai bien mit la date en format Lun 23 Avr 2018 - 15:59
J'ai renseigné le fichier config avec mon forum et les identifiants
Je ne trouve pas d'autres erreurs avec pour référence "KeyError F3"

Pouvez-vous m'aider ?
Merci d'avance,
Cordialement.

**Comment by zsecunix** [comment]
Bonjour,

J'ai exactement la même erreur : 

>   File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\lalf\__init__.py", line 58, in main
    bb.export()
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\lalf\node.py", line 112, in export
    self._export_()
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\lalf\forums.py", line 238, in _export_
    self.get_subforums_infos(response.text)
  File "c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\lalf\forums.py", line 262, in get_subforums_infos
    self.forums[oldid].status = 1 if "verrouillé" in alt else 0
KeyError: 'f3'

Une idée ?

**Comment by zsecunix** [comment]
OK, il s'agissait d'un problème de thème. PHPBB3 est celui à utiliser.

**Comment by kepon85** [comment]
J'ai ce même problème "KeyError: 'f3'"
Tu as réussi à t'en sortir ?
De mon côté j'ai testé de passer en PHPBB3 sans plus de succès, j'avais même lu qu'il fallait utiliser un thème temporaire phpbb2 : https://roromis.github.io/Lalf-Forumactif/annexes/theme-temporaire.html

**Comment by ChrysMa** [comment]
Il faut utiliser le thème phpBB2 cf https://roromis.github.io/Lalf-Forumactif/annexes/theme-temporaire
et renseigner la valeur temporary_theme=xxx  dans ton fichier config.cfg
