### ISSUE TITLE
Demande d'évolution

### ISSUE THREAD

**Issue by zsecunix** [Roromis/Lalf-Forumactif#67]
Bonjour,
Il semble que cet outil n'ait pas été mis à jour depuis 3 ans.
Pourriez-vous l'adapter aux dernières modifs faites par Forumactif (phpBB 3.0) ?
Merci pour votre réponse.

**Comment by ArnoHolo** [comment]
Bonjour !

Cet outil fonctionne toujours, je l'ai utilisé il y a quelques heures. Quelle est précisément la demande d'évolution demandée ?

**Comment by bryxfr** [comment]
Hello,

Moi j'ai une erreur avec :
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (IndexError('list index out of range',)), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "C:\Users\frbry\Miniconda3\lib\site-packages\lalf\__init__.py", line 58, in main
    bb.export()
  File "C:\Users\frbry\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "C:\Users\frbry\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "C:\Users\frbry\Miniconda3\lib\site-packages\lalf\node.py", line 116, in export
    child.export()
  File "C:\Users\frbry\Miniconda3\lib\site-packages\lalf\node.py", line 112, in export
    self._export_()
  File "C:\Users\frbry\Miniconda3\lib\site-packages\lalf\ocrusers.py", line 180, in _export_
    (int(lastvisit[2]), month(lastvisit[1]), int(lastvisit[0]), 0, 0, 0, 0, 0,
IndexError: list index out of range

Si tu as une idée ArnoHolo

**Comment by ChrysMa** [comment]
Bonjour
Tu as cette erreur parce que tu n'as pas modifié correctement le profil de l'utilisateur 'administrateur' que tu as renseigné dans config.cfg cf https://roromis.github.io/Lalf-Forumactif/annexes/profil
Assures toi que tu as bien l'année en 4 chiffres derrière le mois

**Comment by rellik777** [comment]
Bonjour,

Est ce que le Lalf est encore fonctionnel ?
J'ai effectué quelques essaies sur un petit forum, mais pas grand chose de concluant 
[debug.log](https://github.com/Roromis/Lalf-Forumactif/files/5579757/debug.log)

Si quelqu'un a des informations je suis preneur.
