### ISSUE TITLE
lalf.session.UnableToConnect: Impossible de se connecter. Vérifiez les identifiants de l'administrateur

### ISSUE THREAD

**Issue by jeffhpc** [Roromis/Lalf-Forumactif#79]
[debug.log](https://github.com/Roromis/Lalf-Forumactif/files/9482157/debug.log)

Bonjour à tous 
Suite au problème https://github.com/Roromis/Lalf-Forumactif/issues/77 corrigé (merci encore), j'ai relancé le script, qui cette fois commence bien son déroulé. 

Sauvegarde ok des émoticones,
récupération des membre (2874)
INFO     : Récupération des groupes
INFO     : Récupération des forums
INFO     : Récupération du forum f46
DEBUG    : Récupération du forum f46 (page 0)
INFO     : Récupération du sujet 9073
INFO     : Récupération du message 103461 (sujet 7684)
INFO     : Récupération du message 103480 (sujet 7684)
INFO     : Récupération du sujet 1276
DEBUG    : Récupération des messages du sujet 1276 (page 0)
INFO     : Récupération du message 11322 (sujet 1276)
INFO     : Récupération du sujet 1109
DEBUG    : Récupération des messages du sujet 1109 (page 0)
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
DEBUG    : Connection au forum
DEBUG    : Récupération du sid
DEBUG    : Récupération du tid
INFO     : La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.

debug log : 
La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.
Sauvegarde de l'état courant.                                                 
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (UnableToConnect()), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/lalf/__init__.py", line 58, in main
    bb.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 116, in export
    child.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 116, in export
    child.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 116, in export
    child.export()
  [Previous line repeated 2 more times]
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 112, in export
    self._export_()
  File "/root/.local/lib/python3.8/site-packages/lalf/posts.py", line 97, in _export_
    response = self.session.get("/t{}p{}-a".format(self.topic.topic_id, self.page))
  File "/root/.local/lib/python3.8/site-packages/lalf/session.py", line 143, in get
    raise UnableToConnect()
lalf.session.UnableToConnect: Impossible de se connecter. Vérifiez les identifiants de l'administrateur

---> vérifiés et ok, script relancé plusieurs fois, erreur identique dès le début à présent.

je suis allé dans chaque fichier .py aux lignes indiquées pour essayer de comprendre le souci, sans succès. 

Une idée ? : / merci d'avance.

**Comment by jeffhpc** [comment]
je viens de voir ce sujet https://github.com/Roromis/Lalf-Forumactif/issues/52

j'ai donc supprimé le save.pickle, le script reprend, deroule une partie puis : 

...
Récupération du membre 2874                                                                                                         
Récupération des groupes                                                                                                            
Récupération des forums                                                                                                             
Récupération du forum f46                                                                                                           
Récupération du sujet 9073                                                                                                          
La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.                                                    
La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.                                                    
La connexion a échoué au moins deux fois, attend 30 secondes avant de réessayer.                                                    
Sauvegarde de l'état courant.                                                                                                       
ERROR    : Une erreur est survenue. Essayez de relancer le script. Si vous rencontrez la même erreur (UnableToConnect()), créez un rapport de bug à l'adresse suivante SI ELLE N'A PAS ENCORE ÉTÉ SIGNALÉE :
https://github.com/Roromis/Lalf-Forumactif/issues
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/lalf/__init__.py", line 58, in main
    bb.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 116, in export
    child.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 116, in export
    child.export()
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 116, in export
    child.export()
  [Previous line repeated 1 more time]
  File "/root/.local/lib/python3.8/site-packages/lalf/node.py", line 112, in export
    self._export_()
  File "/root/.local/lib/python3.8/site-packages/lalf/topics.py", line 64, in _export_
    response = self.session.get("/t{}-a".format(self.topic_id))
  File "/root/.local/lib/python3.8/site-packages/lalf/session.py", line 143, in get
    raise UnableToConnect()
lalf.session.UnableToConnect: Impossible de se connecter. Vérifiez les identifiants de l'administrateur

**Comment by kepon85** [comment]
T'as bien le bon thème comme dans la doc ?

Depuis la doc, le script forum actif à ajouter plein de truc "anti-spam" (ou anti-aspiration... ) du coup je suggère de "ralentir" la récupération pour ne pas passer pour un spammeur.

Moi je ne supprimerai pas le save.pickle ça permet de repartir de là où tu plante.

Dans posts.py, ligne 21 : https://github.com/Roromis/Lalf-Forumactif/blob/56fdd73bbfe0c81d18f00f2173c578097a5aa8cc/lalf/posts.py#L22
Tu peux ajouter `import time`

Puis dans le script tu peux ajouter des "sleep" pour ralentir la récupération 
: `time.sleep(30)`

Exemple avant la ligne 65 https://github.com/Roromis/Lalf-Forumactif/blob/56fdd73bbfe0c81d18f00f2173c578097a5aa8cc/lalf/posts.py#L65
ligne 107 : https://github.com/Roromis/Lalf-Forumactif/blob/56fdd73bbfe0c81d18f00f2173c578097a5aa8cc/lalf/posts.py#L107 

Si ça bloque met plus que 30, ou patiente 24h... bref faut tâtonner... 

Perso j'ai rencontré des difficultés sur la récupération des boîtes e-mail, à un moment mon forum cache toutes les e-mail, il se met en sécurité... Et même si je change d'IP ou quoi, rien n'y fait... faut que je patiente 24h avant que ça revienne...
